channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=24.2
- pip:
  - mlflow==2.22.0
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==3.0.2
name: mlflow-env
